// normaliseDescription.test.ts — A gap you can see beats a gap filled in.
//
// There is no assistant API, so a reply arrives as whatever it arrives as. This
// turns a partial reply into a complete description rather than rejecting it:
// sections the reply skipped are still headed and marked, so somebody reading
// the issue can see what was not covered instead of finding confident invented
// content where the material said nothing.
//
// Idempotence is the assertion that matters most. Running this over its own
// output has to change nothing, or a description grows a new marker every time
// somebody saves.

import { describe, expect, it } from "vitest";

import {
  VALIDATION_MARKER,
  findUnvalidatedSections,
  normaliseDescription,
  stripAttribution,
} from "../src/authoring/normaliseDescription.js";
import type { DescriptionSection } from "../src/authoring/sectionTemplate.js";

/** Three sections, enough to test order without the noise of nine. */
const SECTIONS: readonly DescriptionSection[] = [
  { heading: "Description", guidance: "The problem." },
  { heading: "Risks", guidance: "What could go wrong." },
  { heading: "Out of Scope", guidance: "What this does not cover." },
];

describe("every configured section", () => {
  it("appears, in the configured order, whatever order the reply used", () => {
    const written = normaliseDescription("Risks:\nA VPN drop.\n\nDescription:\nMembers cannot see it.", SECTIONS);

    expect(written.indexOf("Description:")).toBeLessThan(written.indexOf("Risks:"));
    expect(written).toContain("Out of Scope:");
  });

  it("keeps what the reply actually said under each heading", () => {
    const written = normaliseDescription("Description:\nMembers cannot see it.", SECTIONS);

    expect(written).toContain("Members cannot see it.");
  });

  it("marks a section the material did not cover, rather than inventing content", () => {
    const written = normaliseDescription("Description:\nMembers cannot see it.", SECTIONS);

    expect(written).toContain(`Risks:\n${VALIDATION_MARKER}`);
  });

  it("reads a heading that carries its content on the same line", () => {
    const written = normaliseDescription("Risks: none known", SECTIONS);

    expect(written).toContain("Risks:\nnone known");
  });

  it("reads a heading the reply wrote as markdown", () => {
    const written = normaliseDescription("## Description\nMembers cannot see it.", SECTIONS);

    expect(written).toContain("Members cannot see it.");
  });
});

describe("running it twice", () => {
  it("changes nothing, so markers cannot accumulate", () => {
    // The property that stops a description growing a new marker on every save.
    const once = normaliseDescription("Description:\nMembers cannot see it.", SECTIONS);
    const twice = normaliseDescription(once, SECTIONS);

    expect(twice).toBe(once);
  });

  it("changes nothing on a description that was already complete", () => {
    const complete = normaliseDescription(
      "Description:\nA.\n\nRisks:\nB.\n\nOut of Scope:\nC.",
      SECTIONS,
    );

    expect(normaliseDescription(complete, SECTIONS)).toBe(complete);
  });
});

describe("an empty template", () => {
  it("returns the description as written, since free-form is a real choice", () => {
    expect(normaliseDescription("Just some prose.", [])).toBe("Just some prose.");
  });
});

describe("claims of assistant authorship", () => {
  it("are removed, because a marker means missing information and not a disclaimer", () => {
    expect(stripAttribution("This was generated by AI. Members cannot see it.")).toBe(
      "Members cannot see it.",
    );
  });

  it("are removed however they were phrased", () => {
    expect(stripAttribution("As an AI language model, I suggest this.")).not.toMatch(/ai/i);
    expect(stripAttribution("AI-generated draft follows.")).not.toMatch(/ai-generated/i);
  });

  it("leave the real content alone", () => {
    const text = "Members cannot see their enrolment status.";

    expect(stripAttribution(text)).toBe(text);
  });

  it("are removed during normalisation too, not only on their own", () => {
    const written = normaliseDescription(
      "Description:\nDrafted by an assistant. Members cannot see it.",
      SECTIONS,
    );

    expect(written).toContain("Members cannot see it.");
    expect(written).not.toMatch(/drafted by an assistant/i);
  });
});

describe("saying which sections still need validating", () => {
  it("names them, so the gaps are actionable rather than merely visible", () => {
    const written = normaliseDescription("Description:\nMembers cannot see it.", SECTIONS);

    expect(findUnvalidatedSections(written, SECTIONS)).toEqual(["Risks", "Out of Scope"]);
  });

  it("names none when every section was covered", () => {
    const written = normaliseDescription(
      "Description:\nA.\n\nRisks:\nB.\n\nOut of Scope:\nC.",
      SECTIONS,
    );

    expect(findUnvalidatedSections(written, SECTIONS)).toHaveLength(0);
  });
});
